using System.Collections.Generic;
namespace HollowKnightDiscordRPC {
    public class SceneData {
        public static Dictionary<string, string[]> sceneData = new Dictionary<string, string[]>() {
            {"BetaEnd", new string[3] {"", "Hollow Knight", ""}},
            {"Knight Pickup", new string[3] {"", "Hollow Knight", ""}},
            {"Menu_Credits", new string[3] {"", "Hollow Knight", ""}},
            {"Opening_Sequence", new string[3] {"", "Hollow Knight", ""}},
            {"PermaDeath_Unlock", new string[3] {"", "Hollow Knight", ""}},
            {"Pre_Menu_Intro", new string[3] {"", "Hollow Knight", ""}},
            {"PermaDeath", new string[3] {"", "Hollow Knight", ""}},
            {"Prologue_Excerpt", new string[3] {"", "Hollow Knight", ""}},
            {"Menu_Title", new string[3] {"Loading", "Hollow Knight", ""}},
            {"Cinematic_Stag_travel", new string[3] {"Fast Travel", "Travelling", "travel"}},
            {"Cinematic_Ending_A", new string[3] {"Hollow Knight", "Hollow Knight", ""}},
            {"Cinematic_Ending_B", new string[3] {"Sealed Siblings", "Hollow Knight", ""}},
            {"Cinematic_Ending_C", new string[3] {"Dream No More", "Hollow Knight", ""}},
            {"Cinematic_Ending_D", new string[3] {"Embrace The Void", "Hollow Knight", ""}},
            {"Cinematic_Ending_E", new string[3] {"Embrace The Void", "Hollow Knight", ""}},
            {"Cinematic_MrMushroom", new string[3] {"Passing of The Age", "Hollow Knight", ""}},
            {"Cutscene_Boss_Door", new string[3] {"", "Hollow Knight", ""}},
            {"End_Credits", new string[3] {"Credits", "Hollow Knight", ""}},
            {"End_Game_Completion", new string[3] {"Credits", "Hollow Knight", ""}},
            {"Intro_Cutscene", new string[3] {"", "Hollow Knight", ""}},
            {"Intro_Cutscene_Prologue", new string[3] {"Prologue", "Hollow Knight", ""}},
            {"Quit_To_Menu", new string[3] {"Quitting To Menu", "Hollow Knight", ""}},
            // scenes sorted by area
            {"Abyss_02", new string[3] { "Ancient Basin", "Ancient Basin", "basin"}},
            {"Abyss_03", new string[3] { "Ancient Basin - Tram Station", "Ancient Basin", "basin"}},
            {"Abyss_04", new string[3] { "Ancient Basin", "Ancient Basin", "basin"}},
            {"Abyss_05", new string[3] { "Ancient Basin - Palace Grounds", "Ancient Basin", "basin"}},
            {"Abyss_16", new string[3] { "Ancient Basin", "Ancient Basin", "basin"}},
            {"Abyss_17", new string[3] { "Ancient Basin", "Ancient Basin", "basin"}},
            {"Abyss_18", new string[3] { "Ancient Basin", "Ancient Basin", "basin"}},
            {"Abyss_19", new string[3] { "Ancient Basin", "Ancient Basin", "basin"}},
            {"Abyss_20", new string[3] { "Ancient Basin", "Ancient Basin", "basin"}},
            {"Abyss_21", new string[3] { "Ancient Basin", "Ancient Basin", "basin"}},
            {"Abyss_22", new string[3] { "Ancient Basin - Hidden Station", "Ancient Basin", "basin"}},
            {"Room_nailsmith", new string[3] { "City of Tears - Nailsmith's Hut", "City of Tears", "city"}},
            {"Ruins_House_01", new string[3] { "City of Tears", "City of Tears", "city"}},
            {"Ruins_House_02", new string[3] { "City of Tears", "City of Tears", "city"}},
            {"Ruins_House_03", new string[3] { "City of Tears - Eternal Emilitia's Room", "City of Tears", "city"}},
            {"Ruins_Elevator", new string[3] { "City of Tears - Pleasure House", "City of Tears", "city"}},
            {"Ruins_Bathhouse", new string[3] { "City of Tears - Pleasure House", "City of Tears", "city"}},
            {"Ruins1_01", new string[3] { "City of Tears", "City of Tears", "city"}},
            {"Ruins1_02", new string[3] { "City of Tears", "City of Tears", "city"}},
            {"Ruins1_03", new string[3] { "City of Tears", "City of Tears", "city"}},
            {"Ruins1_04", new string[3] { "City of Tears", "City of Tears", "city"}},
            {"Ruins1_05", new string[3] { "City of Tears", "City of Tears", "city"}},
            {"Ruins1_05b", new string[3] { "City of Tears", "City of Tears", "city"}},
            {"Ruins1_05c", new string[3] { "City of Tears", "City of Tears", "city"}},
            {"Ruins1_06", new string[3] { "City of Tears", "City of Tears", "city"}},
            {"Ruins1_09", new string[3] { "City of Tears", "City of Tears", "city"}},
            {"Ruins1_17", new string[3] { "City of Tears", "City of Tears", "city"}},
            {"Ruins1_18", new string[3] { "City of Tears", "City of Tears", "city"}},
            {"Ruins1_23", new string[3] { "City of Tears - Soul Sanctum", "City of Tears", "city"}},
            {"Ruins1_24", new string[3] { "City of Tears - Soul Sanctum", "City of Tears", "city"}},
            {"Ruins1_25", new string[3] { "City of Tears - Soul Sanctum", "City of Tears", "city"}},
            {"Ruins1_27", new string[3] { "City of Tears - Fountain Square", "City of Tears", "city"}},
            {"Ruins1_28", new string[3] { "City of Tears - City Storerooms", "City of Tears", "city"}},
            {"Ruins1_29", new string[3] { "City of Tears - City Storerooms", "City of Tears", "city"}},
            {"Ruins1_30", new string[3] { "City of Tears - Soul Sanctum", "City of Tears", "city"}},
            {"Ruins1_31", new string[3] { "City of Tears", "City of Tears", "city"}},
            {"Ruins1_32", new string[3] { "City of Tears - Soul Sanctum", "City of Tears", "city"}},
            {"Ruins2_01", new string[3] { "City of Tears", "City of Tears", "city"}},
            {"Ruins2_01_b", new string[3] { "City of Tears", "City of Tears", "city"}},
            {"Ruins2_03", new string[3] { "City of Tears", "City of Tears", "city"}},
            {"Ruins2_04", new string[3] { "City of Tears", "City of Tears", "city"}},
            {"Ruins2_05", new string[3] { "City of Tears", "City of Tears", "city"}},
            {"Ruins2_06", new string[3] { "City of Tears - King's Station", "City of Tears", "city"}},
            {"Ruins2_07", new string[3] { "City of Tears - King's Station", "City of Tears", "city"}},
            {"Ruins2_08", new string[3] { "City of Tears - King's Station", "City of Tears", "city"}},
            {"Ruins2_09", new string[3] { "City of Tears - King's Station", "City of Tears", "city"}},
            {"Ruins2_10b", new string[3] { "City of Tears", "City of Tears", "city"}},
            {"Ruins2_11", new string[3] { "City of Tears - Tower of Love", "City of Tears", "city"}},
            {"Ruins2_11b", new string[3] { "City of Tears - Tower of Love", "City of Tears", "city"}},
            {"Ruins2_Watcher_Room", new string[3] {"City of Tears - Watcher's Spire", "City of Tears", "city"}},
            {"Abyss_01", new string[3] { "City of Tears", "City of Tears", "city"}},
            {"Mines_01", new string[3] { "Crystal Peak", "Crystal Peak", "mines"}},
            {"Mines_02", new string[3] { "Crystal Peak", "Crystal Peak", "mines"}},
            {"Mines_03", new string[3] { "Crystal Peak", "Crystal Peak", "mines"}},
            {"Mines_04", new string[3] { "Crystal Peak", "Crystal Peak", "mines"}},
            {"Mines_05", new string[3] { "Crystal Peak", "Crystal Peak", "mines"}},
            {"Mines_06", new string[3] { "Crystal Peak - Crystal Heart", "Crystal Peak", "mines"}},
            {"Mines_07", new string[3] { "Crystal Peak", "Crystal Peak", "mines"}},
            {"Mines_10", new string[3] { "Crystal Peak", "Crystal Peak", "mines"}},
            {"Mines_11", new string[3] { "Crystal Peak", "Crystal Peak", "mines"}},
            {"Mines_13", new string[3] { "Crystal Peak", "Crystal Peak", "mines"}},
            {"Mines_16", new string[3] { "Crystal Peak", "Crystal Peak", "mines"}},
            {"Mines_17", new string[3] { "Crystal Peak", "Crystal Peak", "mines"}},
            {"Mines_18", new string[3] { "Crystal Peak", "Crystal Peak", "mines"}},
            {"Mines_19", new string[3] { "Crystal Peak", "Crystal Peak", "mines"}},
            {"Mines_20", new string[3] { "Crystal Peak", "Crystal Peak", "mines"}},
            {"Mines_23", new string[3] { "Crystal Peak", "Crystal Peak", "mines"}},
            {"Mines_24", new string[3] { "Crystal Peak", "Crystal Peak", "mines"}},
            {"Mines_25", new string[3] { "Crystal Peak", "Crystal Peak", "mines"}},
            {"Mines_28", new string[3] { "Crystal Peak", "Crystal Peak", "mines"}},
            {"Mines_29", new string[3] { "Crystal Peak", "Crystal Peak", "mines"}},
            {"Mines_30", new string[3] { "Crystal Peak", "Crystal Peak", "mines"}},
            {"Mines_31", new string[3] { "Crystal Peak", "Crystal Peak", "mines"}},
            {"Mines_32", new string[3] { "Crystal Peak", "Crystal Peak", "mines"}},
            {"Mines_33", new string[3] { "Crystal Peak", "Crystal Peak", "mines"}},
            {"Mines_34", new string[3] { "Crystal Peak - Hallownest's Crown", "Crystal Peak", "mines"}},
            {"Mines_35", new string[3] { "Crystal Peak", "Crystal Peak", "mines"}},
            {"Mines_36", new string[3] { "Crystal Peak", "Crystal Peak", "mines"}},
            {"Mines_37", new string[3] { "Crystal Peak", "Crystal Peak", "mines"}},
            {"Room_Mask_Maker", new string[3] { "Deepnest - Mask Maker's room", "Deepnest", "deepnest"}},
            {"Deepnest_01b", new string[3] { "Deepnest", "Deepnest", "deepnest"}},
            {"Deepnest_02", new string[3] { "Deepnest", "Deepnest", "deepnest"}},
            {"Deepnest_03", new string[3] { "Deepnest", "Deepnest", "deepnest"}},
            {"Deepnest_09", new string[3] { "Deepnest - Distant Stag Station", "Deepnest", "deepnest"}},
            {"Deepnest_10", new string[3] { "Deepnest - Distant Village", "Deepnest", "deepnest"}},
            {"Deepnest_14", new string[3] { "Deepnest - Failed Tramway", "Deepnest", "deepnest"}},
            {"Deepnest_16", new string[3] { "Deepnest", "Deepnest", "deepnest"}},
            {"Deepnest_17", new string[3] { "Deepnest", "Deepnest", "deepnest"}},
            {"Deepnest_26", new string[3] { "Deepnest - Failed Tramway", "Deepnest", "deepnest"}},
            {"Deepnest_26b", new string[3] { "Deepnest - Failed Tramway", "Deepnest", "deepnest"}},
            {"Deepnest_30", new string[3] { "Deepnest - Hot Spring", "Deepnest", "deepnest"}},
            {"Deepnest_31", new string[3] { "Deepnest", "Deepnest", "deepnest"}},
            {"Deepnest_32", new string[3] { "Deepnest", "Deepnest", "deepnest"}},
            {"Deepnest_33", new string[3] { "Deepnest", "Deepnest", "deepnest"}},
            {"Deepnest_34", new string[3] { "Deepnest", "Deepnest", "deepnest"}},
            {"Deepnest_35", new string[3] { "Deepnest", "Deepnest", "deepnest"}},
            {"Deepnest_36", new string[3] { "Deepnest", "Deepnest", "deepnest"}},
            {"Deepnest_37", new string[3] { "Deepnest", "Deepnest", "deepnest"}},
            {"Deepnest_38", new string[3] {"Deepnest", "Deepnest", "deepnest"}},
            {"Deepnest_39", new string[3] { "Deepnest", "Deepnest", "deepnest"}},
            {"Deepnest_40", new string[3] { "Deepnest", "Deepnest", "deepnest"}},
            {"Deepnest_41", new string[3] { "Deepnest", "Deepnest", "deepnest"}},
            {"Deepnest_42", new string[3] { "Deepnest", "Deepnest", "deepnest"}},
            {"Deepnest_43", new string[3] { "Deepnest", "Deepnest", "deepnest"}},
            {"Deepnest_44", new string[3] { "Deepnest", "Deepnest", "deepnest"}},
            {"Deepnest_45_v02", new string[3] { "Deepnest - Weaver's Den", "Deepnest", "deepnest"}},
            {"Deepnest_Spider_Town", new string[3] { "Deepnest - Weaver's Den", "Deepnest", "deepnest"}},
            {"Room_spider_small", new string[3] { "Deepnest - Distant Village", "Deepnest", "deepnest"}},
            {"Abyss_03_b", new string[3] { "Deepnest - Tram Station", "Deepnest", "deepnest"}},
            {"Tutorial_01", new string[3] {"King's Pass", "Dirtmouth", "dirtmouth"}},
            {"Town", new string[3] { "Dirtmouth - The Fading Town", "Dirtmouth", "dirtmouth"}},
            {"Room_Town_Stag_Station", new string[3] { "Dirtmouth - Stag Station", "Dirtmouth", "dirtmouth"}},
            {"Room_mapper", new string[3] { "Dirtmouth - Iselda's Shop", "Dirtmouth", "dirtmouth"}},
            {"Room_shop", new string[3] { "Dirtmouth - Sly's Shop", "Dirtmouth", "dirtmouth"}},
            {"Room_Sly_Storeroom", new string[3] { "Dirtmouth - Sly's Basement", "Dirtmouth", "dirtmouth"}},
            {"Room_Bretta", new string[3] { "Dirtmouth - Bretta's House", "Dirtmouth", "dirtmouth"}},
            {"Room_Bretta_Basement", new string[3] { "Dirtmouth - Bretta's Basement", "Dirtmouth", "dirtmouth"}},
            {"Room_Ouiji", new string[3] { "Dirtmouth - Jiji's Room", "Dirtmouth", "dirtmouth"}},
            {"Room_Jinn", new string[3] { "Dirtmouth - Jinn's Cave", "Dirtmouth", "dirtmouth"}},
            {"Grimm_Divine", new string[3] {"Dirtmouth - Divine's Tent", "Dirtmouth", "dirtmouth"}},
            {"Grimm_Main_Tent", new string[3] { "Dirtmouth - Grimm", "Dirtmouth", "dirtmouth"}},
            {"Grimm_Nightmare", new string[3] { "Nightmare King Grimm", "Dirtmouth", "dirtmouth"}},
            {"Dream_Nailcollection", new string[3] { "Dream Realm - Forgotten Dream", "Dream Realm", "dream"}},
            {"Dream_01_False_Knight", new string[3] { "Dream Realm - False Knight", "Dream Realm", "dream"}},
            {"Dream_02_Mage_Lord", new string[3] { "Dream Realm - Soul Tyrant", "Dream Realm", "dream"}},
            {"Dream_03_Infected_Knight", new string[3] { "Dream Realm - Lost Kin", "Dream Realm", "dream"}},
            {"Dream_04_White_Defender", new string[3] { "Dream Realm - White Defender", "Dream Realm", "dream"}},
            {"Dream_Mighty_Zote", new string[3] { "Dream Realm - Grey Prince Zote", "Dream Realm", "dream"}},
            {"Dream_Guardian_Hegemol", new string[3] { "Dream Realm - Herrah the Beast", "Dream Realm", "dream"}},
            {"Dream_Guardian_Lurien", new string[3] { "Dream Realm - Lurien the Watcher", "Dream Realm", "dream"}},
            {"Dream_Guardian_Monomon", new string[3] { "Dream Realm - Monomon the Teacher", "Dream Realm", "dream"}},
            {"Dream_Backer_Shrine", new string[3] { "Dream Realm - Shrine of Believers", "Dream Realm", "dream"}},
            {"Dream_Room_Believer_Shrine", new string[3] { "Dream Realm - Shrine of Believers", "Dream Realm", "dream"}},
            {"Dream_Abyss", new string[3] { "Dream Realm - Birthplace ", "Dream Realm", "dream"}},
            {"Dream_Final_Boss", new string[3] { "The Radiance", "Dream Realm", "dream"}},
            {"Fungus3_01", new string[3] { "Fog Canyon", "Fog Canyon", "canyon"}},
            {"Fungus3_02", new string[3] { "Fog Canyon", "Fog Canyon", "canyon"}},
            {"Fungus3_03", new string[3] { "Fog Canyon", "Fog Canyon", "canyon"}},
            {"Fungus3_24", new string[3] { "Fog Canyon", "Fog Canyon", "canyon"}},
            {"Fungus3_25", new string[3] { "Fog Canyon", "Fog Canyon", "canyon"}},
            {"Fungus3_25b", new string[3] { "Fog Canyon", "Fog Canyon", "canyon"}},
            {"Fungus3_26", new string[3] { "Fog Canyon", "Fog Canyon", "canyon"}},
            {"Fungus3_27", new string[3] { "Fog Canyon", "Fog Canyon", "canyon"}},
            {"Fungus3_28", new string[3] { "Fog Canyon", "Fog Canyon", "canyon"}},
            {"Fungus3_30", new string[3] { "Fog Canyon", "Fog Canyon", "canyon"}},
            {"Fungus3_35", new string[3] { "Fog Canyon", "Fog Canyon", "canyon"}},
            {"Fungus3_44", new string[3] { "Fog Canyon - Overgrown Mound", "Fog Canyon", "canyon"}},
            {"Fungus3_47", new string[3] { "Fog Canyon - Teacher's Archives", "Fog Canyon", "canyon"}},
            {"Fungus3_archive", new string[3] { "Fog Canyon - Teacher's Archives", "Fog Canyon", "canyon"}},
            {"Fungus3_archive_02", new string[3] { "Fog Canyon - Teacher's Archives", "Fog Canyon", "canyon"}},
            {"Room_Fungus_Shaman", new string[3] { "Fog Canyon - Overgrown Mound", "Fog Canyon", "canyon"}},
            {"Room_Charm_Shop", new string[3] { "Forgotten Crossroads - Salubra's Shop", "Forgotten Crossroads", "crossroads"}},
            {"Room_Mender_House", new string[3] { "Forgotten Crossroads - Menderbug's House", "Forgotten Crossroads", "crossroads"}},
            {"Room_temple", new string[3] { "Forgotten Crossroads - Black Egg Temple", "Forgotten Crossroads", "crossroads"}},
            {"Room_ruinhouse", new string[3] { "Forgotten Crossroads - Sly's House", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_01", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_02", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_03", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_04", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_05", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_06", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_07", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_08", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_09", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_10", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_11_alt", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_12", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_13", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_14", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_15", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_16", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_18", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_19", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_21", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_22", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_25", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_27", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_30", new string[3] { "Forgotten Crossroads - Hot Spring", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_31", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_33", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_35", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_36", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_37", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_38", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_39", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_40", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_42", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_43", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_45", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_46", new string[3] { "Forgotten Crossroads - Tram Station", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_ShamanTemple", new string[3] { "Forgotten Crossroads - Ancestral Mound", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_47", new string[3] { "Forgotten Crossroads - Stag Station", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_48", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_49", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_49b", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Crossroads_52", new string[3] { "Forgotten Crossroads", "Forgotten Crossroads", "crossroads"}},
            {"Room_Final_Boss_Atrium", new string[3] {"Black Egg Temple", "Forgotten Crossroads", "crossroads"}},
            {"Room_Final_Boss_Core", new string[3] {"The Hollow Knight", "Forgotten Crossroads", "crossroads"}},
            {"Fungus2_01", new string[3] { "Fungal Wastes - Queen's Station", "Fungal Wastes", "fungus"}},
            {"Fungus2_02", new string[3] { "Fungal Wastes - Queen's Station", "Fungal Wastes", "fungus"}},
            {"Fungus2_03", new string[3] { "Fungal Wastes", "Fungal Wastes", "fungus"}},
            {"Fungus2_04", new string[3] { "Fungal Wastes", "Fungal Wastes", "fungus"}},
            {"Fungus2_05", new string[3] { "Fungal Wastes", "Fungal Wastes", "fungus"}},
            {"Fungus2_06", new string[3] { "Fungal Wastes", "Fungal Wastes", "fungus"}},
            {"Fungus2_07", new string[3] { "Fungal Wastes", "Fungal Wastes", "fungus"}},
            {"Fungus2_08", new string[3] { "Fungal Wastes", "Fungal Wastes", "fungus"}},
            {"Fungus2_09", new string[3] { "Fungal Wastes", "Fungal Wastes", "fungus"}},
            {"Fungus2_10", new string[3] { "Fungal Wastes", "Fungal Wastes", "fungus"}},
            {"Fungus2_11", new string[3] { "Fungal Wastes", "Fungal Wastes", "fungus"}},
            {"Fungus2_12", new string[3] { "Fungal Wastes", "Fungal Wastes", "fungus"}},
            {"Fungus2_13", new string[3] { "Fungal Wastes", "Fungal Wastes", "fungus"}},
            {"Fungus2_14", new string[3] { "Fungal Wastes - Mantis Village ", "Fungal Wastes", "fungus"}},
            {"Fungus2_15", new string[3] { "Fungal Wastes - Mantis Lords", "Fungal Wastes", "fungus"}},
            {"Fungus2_17", new string[3] { "Fungal Wastes", "Fungal Wastes", "fungus"}},
            {"Fungus2_18", new string[3] { "Fungal Wastes", "Fungal Wastes", "fungus"}},
            {"Fungus2_19", new string[3] { "Fungal Wastes", "Fungal Wastes", "fungus"}},
            {"Fungus2_20", new string[3] { "Fungal Wastes", "Fungal Wastes", "fungus"}},
            {"Fungus2_21", new string[3] { "Fungal Wastes", "Fungal Wastes", "fungus"}},
            {"Fungus2_23", new string[3] { "Fungal Wastes", "Fungal Wastes", "fungus"}},
            {"Fungus2_25", new string[3] { "Fungal Wastes", "Fungal Wastes", "fungus"}},
            {"Fungus2_26", new string[3] { "Fungal Wastes", "Fungal Wastes", "fungus"}},
            {"Fungus2_28", new string[3] { "Fungal Wastes", "Fungal Wastes", "fungus"}},
            {"Fungus2_29", new string[3] { "Fungal Wastes - Fungal Core", "Fungal Wastes", "fungus"}},
            {"Fungus2_30", new string[3] { "Fungal Wastes - Fungal Core", "Fungal Wastes", "fungus"}},
            {"Fungus2_31", new string[3] { "Fungal Wastes - Mantis Village", "Fungal Wastes", "fungus"}},
            {"Fungus2_32", new string[3] { "Fungal Wastes - Elder Hu's Grave", "Fungal Wastes", "fungus"}},
            {"Fungus2_33", new string[3] { "Fungal Wastes", "Fungal Wastes", "fungus"}},
            {"Fungus2_34", new string[3] { "Fungal Wastes - Queen's Station", "Fungal Wastes", "fungus"}},
            {"Deepnest_01", new string[3] { "Fungal Wastes", "Fungal Wastes", "fungus"}}, // fungal
            {"Room_nailmaster_02", new string[3] { "Greenpath - Sheo's Hut", "Greenpath", "greenpath"}}, // add area
            {"Room_Slug_Shrine", new string[3] { "Greenpath - Lake of Unn", "Greenpath", "greenpath"}},
            {"Fungus1_01", new string[3] { "Greenpath", "Greenpath", "greenpath"}},
            {"Fungus1_01b", new string[3] { "Greenpath", "Greenpath", "greenpath"}},
            {"Fungus1_02", new string[3] { "Greenpath", "Greenpath", "greenpath"}},
            {"Fungus1_03", new string[3] { "Greenpath", "Greenpath", "greenpath"}},
            {"Fungus1_04", new string[3] { "Greenpath", "Greenpath", "greenpath"}},
            {"Fungus1_05", new string[3] { "Greenpath", "Greenpath", "greenpath"}},
            {"Fungus1_06", new string[3] { "Greenpath", "Greenpath", "greenpath"}},
            {"Fungus1_07", new string[3] { "Greenpath", "Greenpath", "greenpath"}},
            {"Fungus1_08", new string[3] { "Greenpath", "Greenpath", "greenpath"}},
            {"Fungus1_09", new string[3] { "Greenpath", "Greenpath", "greenpath"}},
            {"Fungus1_10", new string[3] { "Greenpath", "Greenpath", "greenpath"}},
            {"Fungus1_11", new string[3] { "Greenpath", "Greenpath", "greenpath"}},
            {"Fungus1_12", new string[3] { "Greenpath", "Greenpath", "greenpath"}},
            {"Fungus1_13", new string[3] { "Greenpath", "Greenpath", "greenpath"}},
            {"Fungus1_14", new string[3] { "Greenpath", "Greenpath", "greenpath"}},
            {"Fungus1_15", new string[3] { "Greenpath", "Greenpath", "greenpath"}},
            {"Fungus1_16_alt", new string[3] {"Greenpath - Stag Station", "Greenpath", "greenpath"}},
            {"Fungus1_17", new string[3] { "Greenpath", "Greenpath", "greenpath"}},
            {"Fungus1_19", new string[3] { "Greenpath", "Greenpath", "greenpath"}},
            {"Fungus1_20_v02", new string[3] { "Greenpath", "Greenpath", "greenpath"}},
            {"Fungus1_21", new string[3] { "Greenpath", "Greenpath", "greenpath"}},
            {"Fungus1_22", new string[3] { "Greenpath", "Greenpath", "greenpath"}},
            {"Fungus1_23", new string[3] { "Greenpath", "Greenpath", "greenpath"}},
            {"Fungus1_24", new string[3] { "Queen's Garden", "Greenpath", "greenpath"}},
            {"Fungus1_25", new string[3] { "Greenpath", "Greenpath", "greenpath"}},
            {"Fungus1_26", new string[3] { "Greenpath - Lake of Unn", "Greenpath", "greenpath"}},
            {"Fungus1_28", new string[3] { "Greenpath", "Greenpath", "greenpath"}},
            {"Fungus1_29", new string[3] { "Greenpath", "Greenpath", "greenpath"}},
            {"Fungus1_30", new string[3] { "Greenpath", "Greenpath", "greenpath"}},
            {"Fungus1_31", new string[3] { "Greenpath", "Greenpath", "greenpath"}},
            {"Fungus1_32", new string[3] { "Greenpath", "Greenpath", "greenpath"}},
            {"Fungus1_34", new string[3] { "Greenpath", "Greenpath", "greenpath"}},
            {"Fungus1_35", new string[3] { "Greenpath - Stone Sanctuary", "Greenpath", "greenpath"}},
            {"Fungus1_36", new string[3] { "Greenpath - Stone Sanctuary", "Greenpath", "greenpath"}},
            {"Fungus1_37", new string[3] { "Greenpath", "Greenpath", "greenpath"}},
            {"Fungus1_Slug", new string[3] { "Greenpath - Lake of Unn", "Greenpath", "greenpath"}},
            {"Room_nailmaster", new string[3] { "Howling Cliffs - Mato's Hut", "Howling Cliffs", "cliffs"}}, // add area
            {"Cliffs_01", new string[3] { "Howling Cliffs", "Howling Cliffs", "cliffs"}},
            {"Cliffs_02", new string[3] { "Howling Cliffs", "Howling Cliffs", "cliffs"}},
            {"Cliffs_03", new string[3] { "Howling Cliffs - Stag Nest", "Howling Cliffs", "cliffs"}},
            {"Cliffs_04", new string[3] { "Howling Cliffs", "Howling Cliffs", "cliffs"}},
            {"Cliffs_05", new string[3] { "Howling Cliffs - Joni's Repose", "Howling Cliffs", "cliffs"}},
            {"Cliffs_06", new string[3] { "Howling Cliffs", "Howling Cliffs", "cliffs"}},
            {"Room_nailmaster_03", new string[3] { "Kingdom's Edge - Oro's Hut", "Kingdom's Edge", "edge"}}, // add area
            {"Room_Colosseum_01", new string[3] { "Kingdom's Edge - Colosseum of Fools", "Kingdom's Edge", "edge"}},
            {"Room_Colosseum_02", new string[3] {"Kingdom's Edge - Colosseum of Fools", "Kingdom's Edge", "edge"}},
            {"Room_Colosseum_Bronze", new string[3] { "Kingdom's Edge - Trial of the Warrior", "Kingdom's Edge", "edge"}},
            {"Room_Colosseum_Silver", new string[3] { "Kingdom's Edge - Trial of the Conqueror", "Kingdom's Edge", "edge"}},
            {"Room_Colosseum_Gold", new string[3] { "Kingdom's Edge - Trial of the Fool", "Kingdom's Edge", "edge"}},
            {"Room_Colosseum_Spectate", new string[3] { "Kingdom's Edge - Colosseum of Fools", "Kingdom's Edge", "edge"}},
            {"Deepnest_East_01", new string[3] { "Kingdom's Edge", "Kingdom's Edge", "edge"}}, // edge
            {"Deepnest_East_02", new string[3] { "Kingdom's Edge", "Kingdom's Edge", "edge"}},
            {"Deepnest_East_03", new string[3] { "Kingdom's Edge", "Kingdom's Edge", "edge"}},
            {"Deepnest_East_04", new string[3] { "Kingdom's Edge", "Kingdom's Edge", "edge"}},
            {"Deepnest_East_06", new string[3] { "Kingdom's Edge", "Kingdom's Edge", "edge"}},
            {"Deepnest_East_07", new string[3] { "Kingdom's Edge", "Kingdom's Edge", "edge"}},
            {"Deepnest_East_08", new string[3] { "Kingdom's Edge", "Kingdom's Edge", "edge"}},
            {"Deepnest_East_09", new string[3] { "Kingdom's Edge", "Kingdom's Edge", "edge"}},
            {"Deepnest_East_10", new string[3] { "Kingdom's Edge", "Kingdom's Edge", "edge"}},
            {"Deepnest_East_11", new string[3] { "Kingdom's Edge", "Kingdom's Edge", "edge"}},
            {"Deepnest_East_12", new string[3] { "Kingdom's Edge", "Kingdom's Edge", "edge"}},
            {"Deepnest_East_13", new string[3] { "Kingdom's Edge", "Kingdom's Edge", "edge"}},
            {"Deepnest_East_14", new string[3] { "Kingdom's Edge", "Kingdom's Edge", "edge"}},
            {"Deepnest_East_15", new string[3] { "Kingdom's Edge", "Kingdom's Edge", "edge"}},
            {"Deepnest_East_16", new string[3] { "Kingdom's Edge", "Kingdom's Edge", "edge"}},
            {"Deepnest_East_17", new string[3] { "Kingdom's Edge", "Kingdom's Edge", "edge"}},
            {"Deepnest_East_18", new string[3] { "Kingdom's Edge", "Kingdom's Edge", "edge"}},
            {"Deepnest_East_Hornet", new string[3] { "Kingdom's Edge", "Kingdom's Edge", "edge"}},
            {"Room_Wyrm", new string[3] { "Kingdom's Edge - Cast-Off Shell", "Kingdom's Edge", "edge"}},
            {"Abyss_03_c", new string[3] { "Kingdom's Edge - Tram Station", "Kingdom's Edge", "edge"}},
            {"Hive_01", new string[3] { "Kingdom's Edge - The Hive", "Kingdom's Edge", "edge"}},
            {"Hive_02", new string[3] { "Kingdom's Edge - The Hive", "Kingdom's Edge", "edge"}},
            {"Hive_03", new string[3] { "Kingdom's Edge - The Hive", "Kingdom's Edge", "edge"}},
            {"Hive_04", new string[3] { "Kingdom's Edge - The Hive", "Kingdom's Edge", "edge"}},
            {"Hive_05", new string[3] { "Kingdom's Edge - Hive Knight", "Kingdom's Edge", "edge"}},
            {"Fungus3_04", new string[3] { "Queen's Gardens", "Queen's Gardens", "gardens"}},
            {"Fungus3_05", new string[3] { "Queen's Gardens", "Queen's Gardens", "gardens"}},
            {"Fungus3_08", new string[3] { "Queen's Gardens", "Queen's Gardens", "gardens"}},
            {"Fungus3_10", new string[3] { "Queen's Gardens", "Queen's Gardens", "gardens"}},
            {"Fungus3_11", new string[3] { "Queen's Gardens", "Queen's Gardens", "gardens"}},
            {"Fungus3_13", new string[3] { "Queen's Gardens", "Queen's Gardens", "gardens"}},
            {"Fungus3_21", new string[3] { "Queen's Gardens", "Queen's Gardens", "gardens"}},
            {"Fungus3_22", new string[3] { "Queen's Gardens", "Queen's Gardens", "gardens"}},
            {"Fungus3_23", new string[3] { "Queen's Gardens - Traitor Lord", "Queen's Gardens", "gardens"}},
            {"Fungus3_34", new string[3] { "Queen's Gardens", "Queen's Gardens", "gardens"}},
            {"Fungus3_39", new string[3] { "Queen's Gardens", "Queen's Gardens", "gardens"}},
            {"Fungus3_40", new string[3] { "Queen's Gardens - Stag Station", "Queen's Gardens", "gardens"}},
            {"Fungus3_48", new string[3] { "Queen's Gardens", "Queen's Gardens", "gardens"}},
            {"Fungus3_49", new string[3] {"Queen's Gardens - The Traitors' Child's grave", "Queen's Gardens", "gardens"}},
            {"Fungus3_50", new string[3] { "Queen's Gardens", "Queen's Gardens", "gardens"}},
            {"Room_Queen", new string[3] { "Queen's Gardens - White Lady's Room", "Queen's Gardens", "gardens"}},
            {"Room_Mansion", new string[3] { "Resting Grounds - Grey Mourner's House", "Resting Grounds", "resting_grounds"}},
            {"Crossroads_46b", new string[3] { "Resting Grounds - Tram Station", "Resting Grounds", "resting_grounds"}},
            {"Crossroads_50", new string[3] { "Resting Grounds - Blue Lake", "Resting Grounds", "resting_grounds"}},
            {"Ruins2_10", new string[3] { "Resting Grounds", "Resting Grounds", "resting_grounds"}}, // grounds
            {"RestingGrounds_02", new string[3] { "Resting Grounds", "Resting Grounds", "resting_grounds"}},
            {"RestingGrounds_04", new string[3] { "Resting Grounds", "Resting Grounds", "resting_grounds"}},
            {"RestingGrounds_05", new string[3] { "Resting Grounds", "Resting Grounds", "resting_grounds"}},
            {"RestingGrounds_06", new string[3] { "Resting Grounds", "Resting Grounds", "resting_grounds"}},
            {"RestingGrounds_07", new string[3] { "Resting Grounds", "Resting Grounds", "resting_grounds"}},
            {"RestingGrounds_08", new string[3] { "Resting Grounds", "Resting Grounds", "resting_grounds"}},
            {"RestingGrounds_09", new string[3] { "Resting Grounds - Stag Station", "Resting Grounds", "resting_grounds"}},
            {"RestingGrounds_10", new string[3] { "Resting Grounds", "Resting Grounds", "resting_grounds"}},
            {"RestingGrounds_12", new string[3] { "Resting Grounds", "Resting Grounds", "resting_grounds"}},
            {"RestingGrounds_17", new string[3] { "Resting Grounds", "Resting Grounds", "resting_grounds"}},
            {"Waterways_01", new string[3] { "Royal Waterways", "Royal Waterways", "waterways"}},
            {"Waterways_02", new string[3] { "Royal Waterways", "Royal Waterways", "waterways"}},
            {"Waterways_03", new string[3] { "Royal Waterways", "Royal Waterways", "waterways"}},
            {"Waterways_04", new string[3] { "Royal Waterways", "Royal Waterways", "waterways"}},
            {"Waterways_04b", new string[3] { "Royal Waterways", "Royal Waterways", "waterways"}},
            {"Waterways_05", new string[3] { "Royal Waterways", "Royal Waterways", "waterways"}},
            {"Waterways_06", new string[3] { "Royal Waterways", "Royal Waterways", "waterways"}},
            {"Waterways_07", new string[3] { "Royal Waterways", "Royal Waterways", "waterways"}},
            {"Waterways_08", new string[3] { "Royal Waterways", "Royal Waterways", "waterways"}},
            {"Waterways_09", new string[3] { "Royal Waterways", "Royal Waterways", "waterways"}},
            {"Waterways_12", new string[3] { "Royal Waterways", "Royal Waterways", "waterways"}},
            {"Waterways_13", new string[3] { "Royal Waterways - Isma's Grove", "Royal Waterways", "waterways"}},
            {"Waterways_14", new string[3] { "Royal Waterways", "Royal Waterways", "waterways"}},
            {"Waterways_15", new string[3] { "Royal Waterways - Ogrim's Cave", "Royal Waterways", "waterways"}},
            {"Abyss_06_Core", new string[3] { "The Abyss", "The Abyss", "abyss"}},
            {"Abyss_08", new string[3] { "The Abyss - Lifeblood Core", "The Abyss", "abyss"}},
            {"Abyss_09", new string[3] { "The Abyss", "The Abyss", "abyss"}},
            {"Abyss_10", new string[3] {"The Abyss", "The Abyss", "abyss"}},
            {"Abyss_12", new string[3] { "The Abyss", "The Abyss", "abyss"}},
            {"Abyss_15", new string[3] { "The Abyss - Birthplace", "The Abyss", "abyss"}},
            {"Abyss_Lighthouse_room", new string[3] {"The Abyss - Lighthouse", "The Abyss", ""}},
            {"Room_Tram", new string[3] { "Lower Tram", "Tram", "tram"}},
            {"Room_Tram_RG", new string[3] { "Upper Tram", "Tram", "tram"}},
            {"White_Palace_01", new string[3] { "White Palace", "White Palace", "palace"}},
            {"White_Palace_02", new string[3] { "White Palace", "White Palace", "palace"}},
            {"White_Palace_03_hub", new string[3] { "White Palace", "White Palace", "palace"}},
            {"White_Palace_04", new string[3] { "White Palace", "White Palace", "palace"}},
            {"White_Palace_05", new string[3] { "White Palace", "White Palace", "palace"}},
            {"White_Palace_06", new string[3] { "White Palace", "White Palace", "palace"}},
            {"White_Palace_07", new string[3] { "White Palace", "White Palace", "palace"}},
            {"White_Palace_08", new string[3] { "White Palace - The Pale King's Workshop", "White Palace", "palace"}},
            {"White_Palace_09", new string[3] { "White Palace - Throne Room", "White Palace", "palace"}},
            {"White_Palace_11", new string[3] { "White Palace", "White Palace", "palace"}},
            {"White_Palace_12", new string[3] { "White Palace", "White Palace", "palace"}},
            {"White_Palace_13", new string[3] { "White Palace", "White Palace", "palace"}},
            {"White_Palace_14", new string[3] { "White Palace", "White Palace", "palace"}},
            {"White_Palace_15", new string[3] { "White Palace", "White Palace", "palace"}},
            {"White_Palace_16", new string[3] { "White Palace", "White Palace", "palace"}},
            {"White_Palace_17", new string[3] { "White Palace - Path of Pain", "White Palace", "palace"}},
            {"White_Palace_18", new string[3] { "White Palace - Path of Pain", "White Palace", "palace"}},
            {"White_Palace_19", new string[3] { "White Palace - Path of Pain", "White Palace", "palace"}},
            {"White_Palace_20", new string[3] { "White Palace - Path of Pain", "White Palace", "palace"}},
            // godmaster content
            {"Room_GG_Shortcut", new string[3] {"Royal Waterways", "Royal Waterways", "waterways"}},
            {"GG_Waterways", new string[3] {"Royal Waterways - Junk Pit", "Royal Waterways", "waterways"}},
            {"GG_Pipeway", new string[3] {"Royal Waterways", "Royal Waterways", "waterways"}},
            {"GG_Boss_Door_Entrance", new string[3] { "Godhome", "Godhome", "godhome"}},
            {"GG_End_Sequence", new string[3] { "Godhome", "Godhome", "godhome"}},
            {"GG_Entrance_Cutscene", new string[3] { "Godhome", "Godhome", "godhome"}},
            {"GG_Unlock", new string[3] { "Godhome", "Godhome", "godhome"}},
            {"GG_Atrium", new string[3] { "Godhome", "Godhome", "godhome"}},
            {"GG_Mighty_Zote", new string[3] { "Godhome - The Eternal Ordeal", "Godhome", "godhome"}},
            {"GG_Atrium_Roof", new string[3] { "Godhome - Pantheon of Hallownest", "Godhome", "godhome"}},
            {"GG_Spa", new string[3] { "Godhome", "Godhome", "godhome"}},
            {"GG_Unlock_Wastes", new string[3] { "Godhome", "Godhome", "godhome"}},
            {"GG_Workshop", new string[3] { "Godhome - Hall of Gods", "Godhome", "godhome"}},
            {"GG_Engine", new string[3] { "Godhome", "Godhome", "godhome"}},
            {"GG_Engine_Root", new string[3] { "Godhome", "Godhome", "godhome"}},
            {"GG_Unn", new string[3] { "Godhome", "Godhome", "godhome"}},
            {"GG_Wyrm", new string[3] { "Godhome", "Godhome", "godhome"}},
            {"GG_Mage_Knight", new string[3] { "Godhome - Soul Warrior", "Godhome", "godhome"}},
            {"GG_Mage_Knight_V", new string[3] { "Godhome - Soul Warrior", "Godhome", "godhome"}},
            {"GG_Soul_Master", new string[3] { "Godhome - Soul Master", "Godhome", "godhome"}},
            {"GG_Soul_Tyrant", new string[3] { "Godhome - Soul Tyrant", "Godhome", "godhome"}},
            {"GG_Dung_Defender", new string[3] { "Godhome - Dung Defender", "Godhome", "godhome"}},
            {"GG_White_Defender", new string[3] { "Godhome - White Defender", "Godhome", "godhome"}},
            {"GG_Watcher_Knights", new string[3] { "Godhome - Watcher Knights", "Godhome", "godhome"}},
            {"GG_Ghost_No_Eyes", new string[3] { "Godhome - No Eyes", "Godhome", "godhome"}},
            {"GG_Ghost_No_Eyes_V", new string[3] { "Godhome - No Eyes", "Godhome", "godhome"}},
            {"GG_Ghost_Xero", new string[3] { "Godhome - Xero", "Godhome", "godhome"}},
            {"GG_Ghost_Xero_V", new string[3] { "Godhome - Xero", "Godhome", "godhome"}},
            {"GG_Ghost_Markoth", new string[3] { "Godhome - Markoth", "Godhome", "godhome"}},
            {"GG_Ghost_Markoth_V", new string[3] { "Godhome - Markoth", "Godhome", "godhome"}},
            {"GG_Ghost_Galien", new string[3] { "Godhome - Galien", "Godhome", "godhome"}},
            {"GG_Ghost_Gorb", new string[3] { "Godhome - Gorb", "Godhome", "godhome"}},
            {"GG_Ghost_Gorb_V", new string[3] { "Godhome - Gorb", "Godhome", "godhome"}},
            {"GG_Ghost_Hu", new string[3] { "Godhome - Elder Hu", "Godhome", "godhome"}},
            {"GG_Ghost_Marmu", new string[3] { "Godhome - Marmu", "Godhome", "godhome"}},
            {"GG_Ghost_Marmu_V", new string[3] { "Godhome - Marmu", "Godhome", "godhome"}},
            {"GG_Nailmasters", new string[3] { "Godhome - Brothers Oro & Mato", "Godhome", "godhome"}},
            {"GG_Painter", new string[3] { "Godhome - Paintmaster Sheo", "Godhome", "godhome"}},
            {"GG_Sly", new string[3] { "Godhome - Great Nailsage Sly", "Godhome", "godhome"}},
            {"GG_Grimm", new string[3] { "Godhome - Grimm", "Godhome", "godhome"}},
            {"GG_Grimm_Nightmare", new string[3] { "Godhome - Nightmare King Grimm", "Godhome", "godhome"}},
            {"GG_Grey_Prince_Zote", new string[3] { "Godhome - Grey Prince Zote", "Godhome", "godhome"}},
            {"GG_Traitor_Lord", new string[3] { "Godhome - Traitor Lord", "Godhome", "godhome"}},
            {"GG_Crystal_Guardian", new string[3] { "Godhome - Crystal Guardian", "Godhome", "godhome"}},
            {"GG_Crystal_Guardian_2", new string[3] { "Godhome - Enraged Guardian", "Godhome", "godhome"}},
            {"GG_God_Tamer", new string[3] { "Godhome - God Tamer", "Godhome", "godhome"}},
            {"GG_Collector", new string[3] { "Godhome - The Collector", "Godhome", "godhome"}},
            {"GG_Collector_V", new string[3] { "Godhome - The Collector", "Godhome", "godhome"}},
            {"GG_Nosk", new string[3] { "Godhome - Nosk", "Godhome", "godhome"}},
            {"GG_Nosk_V", new string[3] { "Godhome - Nosk", "Godhome", "godhome"}},
            {"GG_Nosk_Hornet", new string[3] { "Godhome - Winged Nosk", "Godhome", "godhome"}},
            {"GG_Broken_Vessel", new string[3] { "Godhome - Broken Vessel", "Godhome", "godhome"}},
            {"GG_Lost_Kin", new string[3] { "Godhome - Lost Kin", "Godhome", "godhome"}},
            {"GG_Hive_Knight", new string[3] { "Godhome - Hive Knight", "Godhome", "godhome"}},
            {"GG_Oblobbles", new string[3] { "Godhome - Oblobbles", "Godhome", "godhome"}},
            {"GG_Mantis_Lords", new string[3] { "Godhome - Mantis Lords", "Godhome", "godhome"}},
            {"GG_Flukemarm", new string[3] { "Godhome - Flukemarm", "Godhome", "godhome"}},
            {"GG_Mantis_Lords_V", new string[3] { "Godhome - Sisters of Battle", "Godhome", "godhome"}},
            {"GG_Mega_Moss_Charger", new string[3] { "Godhome - Massive Moss Charger", "Godhome", "godhome"}},
            {"GG_Hornet_1", new string[3] { "Godhome - Hornet", "Godhome", "godhome"}},
            {"GG_Hornet_2", new string[3] { "Godhome - Hornet Sentinel", "Godhome", "godhome"}},
            {"GG_False_Knight", new string[3] { "Godhome - False Knight", "Godhome", "godhome"}},
            {"GG_Failed_Champion", new string[3] { "Godhome - Failed Champion", "Godhome", "godhome"}},
            {"GG_Brooding_Mawlek", new string[3] { "Godhome - Brooding Mawlek", "Godhome", "godhome"}},
            {"GG_Brooding_Mawlek_V", new string[3] { "Godhome - Brooding Mawlek", "Godhome", "godhome"}},
            {"GG_Gruz_Mother", new string[3] { "Godhome - Gruz Mother", "Godhome", "godhome"}},
            {"GG_Gruz_Mother_V", new string[3] { "Godhome - Gruz Mother", "Godhome", "godhome"}},
            {"GG_Uumuu", new string[3] { "Godhome - Uumuu", "Godhome", "godhome"}},
            {"GG_Uumuu_V", new string[3] { "Godhome - Uumuu", "Godhome", "godhome"}},
            {"GG_Vengefly", new string[3] { "Godhome - Vengefly", "Godhome", "godhome"}},
            {"GG_Vengefly_V", new string[3] { "Godhome - Vengefly", "Godhome", "godhome"}},
            {"GG_Radiance", new string[3] { "Godhome - Absolute Radiance", "Godhome", "godhome"}},
            {"GG_Hollow_Knight", new string[3] { "Godhome - Pure Vessel", "Godhome", "godhome"}},
        };
        private static readonly Dictionary<string, bool> excludedScenes = new Dictionary<string, bool>() {
            {"BetaEnd", true},
            {"Knight Pickup", true},
            {"Menu_Credits", true},
            {"Opening_Sequence", true},
            {"PermaDeath_Unlock", true},
            {"Pre_Menu_Intro", true},
            {"PermaDeath", false},
            {"Prologue_Excerpt", true},
            {"Menu_Title", true},
            {"Cinematic_Stag_travel", false },
            {"Cinematic_Ending_A", true},
            {"Cinematic_Ending_B", true},
            {"Cinematic_Ending_C", true},
            {"Cinematic_Ending_D", true},
            {"Cinematic_Ending_E", true},
            {"Cinematic_MrMushroom", true},
            {"Cutscene_Boss_Door", true},
            {"End_Credits", true},
            {"End_Game_Completion", true},
            {"Intro_Cutscene", true},
            {"Intro_Cutscene_Prologue", true},
            {"Quit_To_Menu", true},
        };
        /*
        // Sly's shop and Bretta's House return crossroads instead of dirtmouth... (the only reason i did not use that dict below)
        public static Dictionary<string, string> areas = new Dictionary<string, string>(){
            {"NONE",""},
            {"TEST_AREA","Test area"},
            {"KINGS_PASS","King's Pass"},
            {"CLIFFS","Howling Cliffs "},
            {"TOWN","Dirtmouth"},
            {"CROSSROADS","Forgotten Crossroads"}, 
            {"GREEN_PATH","Greenpath"},
            {"ROYAL_GARDENS","Queen's Gardens"},
            {"FOG_CANYON","Fog Canyon"},
            {"WASTES","Fungal Wastes"},
            {"DEEPNEST","Deepnest"},
            {"HIVE","The Hive"}, // or Kingdom's Edge - The Hive
            {"BONE_FOREST","Bone Forest"}, // cut content
            {"PALACE_GROUNDS","Palace Grounds"},
            {"MINES","Crystal Peak"},
            {"RESTING_GROUNDS","Resting Grounds"},
            {"CITY","City of Tears"},
            {"DREAM_WORLD","Dream Realm"},
            {"COLOSSEUM","Colosseum of Fools"},
            {"ABYSS","Ancient Basin"},
            {"ROYAL_QUARTER","ROYAL_QUARTER"}, // placeholder
            {"WHITE_PALACE","White Palace"},
            {"SHAMAN_TEMPLE","Shaman Temple"},
            {"WATERWAYS","Royal Waterways"},
            {"QUEENS_STATION","Queen's Station"},
            {"OUTSKIRTS","Kingdom's Edge"},
            {"KINGS_STATION","King's Station"},
            {"MAGE_TOWER","Soul Sanctum"}, // ?
            {"TRAM_UPPER","Tram"},
            {"TRAM_LOWER","Tram"},
            {"FINAL_BOSS","The Hollow Knight"},
            {"SOUL_SOCIETY","City of Tears"}, // Soul Sanctum
            {"ACID_LAKE","Greenpath"},
            {"NOEYES_TEMPLE","Greenpath"},
            {"MONOMON_ARCHIVE","Fog Canyon"},
            {"MANTIS_VILLAGE","Fungal Wastes"},
            {"RUINED_TRAMWAY","Failed Tramway"},
            {"DISTANT_VILLAGE","Distant Village"},
            {"ABYSS_DEEP","The Abyss"},
            {"ISMAS_GROVE","Isma's Grove"},
            {"WYRMSKIN","Cast-Off Shell"},
            {"LURIENS_TOWER","City Of Tears"}, // City Of Tears -  Watcher's Spire
            {"LOVE_TOWER","Tower of Love"}, // doesnt work?
            {"GLADE","GLADE"}, // ?
            {"BLUE_LAKE","Blue Lake"},
            {"PEAK","Crystal Peak"}, // ??
            {"JONI_GRAVE","Joni's Repose"}, // doesnt work
            {"OVERGROWN_MOUND","Overgrown Mound"},
            {"CRYSTAL_MOUND","Crystal Mound"},
            {"BEASTS_DEN","Beast's Den"},
            {"GODS_GLORY","Godhome"},
            {"GODSEEKER_WASTE","Royal Waterways"},
        };
        */
        public static string GetSceneArea(string scene) {
            try {
                return sceneData[scene][0];
            }
            catch {
                if (!string.IsNullOrEmpty(scene)) return scene;
                return "Unknown Scene";
            }
        }
        public static bool IsInExcludedScenes(string scene) {
            try {
                return excludedScenes[scene];
            }
            catch {
                return false;
            }
        }
        public static string GetAreaName(string scene) {
            try {
                if (!string.IsNullOrEmpty(sceneData[scene][1])) return sceneData[scene][1];
                return "Hollow Knight";
            }
            catch {
                return "Hollow Knight";
            }
        }
        public static string GetSceneImage(string scene) {
            try {
                return sceneData[scene][2];
            }
            catch {
                return "null";
            }
        }
    }
}